language: java
sudo: false
install: true

jdk:
- oraclejdk8

script:
- mvn clean package

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
notifications:
  email: false
